registry:
  address: 0.0.0.0:8500

service:
  name: platform.srv.session
  externalAddr: 0.0.0.0:8001
  listenAddr: 0.0.0.0:8002
  brokerAddr: 0.0.0.0:8003
  version: v1.0.0
  metadata:
    id: "1"


log:
  path: ../log
  level: debug
  fileSize: 1024000

redis:
  addr: 127.0.0.1:6379
  password:
  maxIdle: 2
  maxActive: 1
