// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package platform_user_srv_session

import (
	fmt "fmt"
	idl "github.com/dy-platform/user-srv-session/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordReq struct {
	UID                  int64    `protobuf:"varint,1,opt,name=uID,proto3" json:"uID,omitempty"`
	ExpireTime           int32    `protobuf:"varint,2,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordReq) Reset()         { *m = RecordReq{} }
func (m *RecordReq) String() string { return proto.CompactTextString(m) }
func (*RecordReq) ProtoMessage()    {}
func (*RecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *RecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordReq.Unmarshal(m, b)
}
func (m *RecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordReq.Marshal(b, m, deterministic)
}
func (m *RecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordReq.Merge(m, src)
}
func (m *RecordReq) XXX_Size() int {
	return xxx_messageInfo_RecordReq.Size(m)
}
func (m *RecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordReq proto.InternalMessageInfo

func (m *RecordReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *RecordReq) GetExpireTime() int32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type RecordResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Token                string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordResp) Reset()         { *m = RecordResp{} }
func (m *RecordResp) String() string { return proto.CompactTextString(m) }
func (*RecordResp) ProtoMessage()    {}
func (*RecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

func (m *RecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResp.Unmarshal(m, b)
}
func (m *RecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResp.Marshal(b, m, deterministic)
}
func (m *RecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResp.Merge(m, src)
}
func (m *RecordResp) XXX_Size() int {
	return xxx_messageInfo_RecordResp.Size(m)
}
func (m *RecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResp proto.InternalMessageInfo

func (m *RecordResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *RecordResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpireTime           int32    `protobuf:"varint,2,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshReq) Reset()         { *m = RefreshReq{} }
func (m *RefreshReq) String() string { return proto.CompactTextString(m) }
func (*RefreshReq) ProtoMessage()    {}
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{2}
}

func (m *RefreshReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshReq.Unmarshal(m, b)
}
func (m *RefreshReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshReq.Marshal(b, m, deterministic)
}
func (m *RefreshReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshReq.Merge(m, src)
}
func (m *RefreshReq) XXX_Size() int {
	return xxx_messageInfo_RefreshReq.Size(m)
}
func (m *RefreshReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshReq proto.InternalMessageInfo

func (m *RefreshReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshReq) GetExpireTime() int32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type RefreshResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RefreshResp) Reset()         { *m = RefreshResp{} }
func (m *RefreshResp) String() string { return proto.CompactTextString(m) }
func (*RefreshResp) ProtoMessage()    {}
func (*RefreshResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{3}
}

func (m *RefreshResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResp.Unmarshal(m, b)
}
func (m *RefreshResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResp.Marshal(b, m, deterministic)
}
func (m *RefreshResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResp.Merge(m, src)
}
func (m *RefreshResp) XXX_Size() int {
	return xxx_messageInfo_RefreshResp.Size(m)
}
func (m *RefreshResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResp proto.InternalMessageInfo

func (m *RefreshResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type QueryReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{4}
}

func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (m *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(m, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

func (m *QueryReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type QueryResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	UID                  int64     `protobuf:"varint,2,opt,name=uID,proto3" json:"uID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{5}
}

func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (m *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(m, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

func (m *QueryResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *QueryResp) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func init() {
	proto.RegisterType((*RecordReq)(nil), "platform.user.srv.session.RecordReq")
	proto.RegisterType((*RecordResp)(nil), "platform.user.srv.session.RecordResp")
	proto.RegisterType((*RefreshReq)(nil), "platform.user.srv.session.RefreshReq")
	proto.RegisterType((*RefreshResp)(nil), "platform.user.srv.session.RefreshResp")
	proto.RegisterType((*QueryReq)(nil), "platform.user.srv.session.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "platform.user.srv.session.QueryResp")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x56, 0x69, 0x9b, 0xab, 0x90, 0xd0, 0x89, 0xa1, 0x64, 0x40, 0x91, 0x29, 0x55,
	0x27, 0x0f, 0x45, 0x8c, 0x2c, 0x08, 0x06, 0xd8, 0x30, 0x20, 0xb1, 0xb6, 0x70, 0x15, 0x11, 0xb4,
	0x36, 0xbe, 0x04, 0xc1, 0x4b, 0xf0, 0xcc, 0xc8, 0x4e, 0x62, 0x75, 0x69, 0x1b, 0xb6, 0xf3, 0xf9,
	0xbb, 0xff, 0xce, 0xff, 0x19, 0x0e, 0x98, 0x98, 0x73, 0xbd, 0x96, 0xc6, 0xea, 0x42, 0xe3, 0xb1,
	0xf9, 0x98, 0x17, 0x4b, 0x6d, 0x57, 0xb2, 0x64, 0xb2, 0x92, 0xed, 0x97, 0xac, 0x81, 0x14, 0x16,
	0x73, 0xa6, 0x0a, 0x13, 0x97, 0x90, 0x28, 0x7a, 0xd1, 0xf6, 0x55, 0xd1, 0x27, 0x1e, 0x42, 0xb7,
	0xbc, 0xbd, 0x1e, 0x45, 0x59, 0x34, 0xed, 0x2a, 0x17, 0xe2, 0x09, 0x00, 0x7d, 0x9b, 0xdc, 0xd2,
	0x63, 0xbe, 0xa2, 0x51, 0x27, 0x8b, 0xa6, 0xb1, 0xda, 0xc8, 0x88, 0x3b, 0x80, 0xa6, 0x9c, 0x0d,
	0x4e, 0x60, 0xe0, 0xa4, 0x5d, 0xec, 0x45, 0x86, 0x33, 0x90, 0xbe, 0x97, 0xcb, 0xa8, 0x70, 0x87,
	0x47, 0x10, 0x17, 0xfa, 0x9d, 0xd6, 0x5e, 0x30, 0x51, 0xd5, 0x41, 0x5c, 0x39, 0xad, 0xa5, 0x25,
	0x7e, 0x73, 0xb3, 0x04, 0x26, 0xda, 0x60, 0xf6, 0xce, 0x73, 0x01, 0xc3, 0xa0, 0xd1, 0x7e, 0x20,
	0x91, 0xc1, 0xe0, 0xbe, 0x24, 0xfb, 0xb3, 0xb5, 0xb1, 0xb8, 0x81, 0xa4, 0x26, 0xfe, 0xf1, 0xce,
	0xda, 0xcf, 0x4e, 0xf0, 0x73, 0xf6, 0xdb, 0x81, 0xfe, 0x43, 0xb5, 0x06, 0x7c, 0x82, 0x5e, 0xe5,
	0x1d, 0x8e, 0xe5, 0xd6, 0x65, 0xc9, 0xb0, 0x9d, 0xf4, 0xac, 0x05, 0xc5, 0x06, 0x9f, 0xa1, 0x5f,
	0x5b, 0x80, 0xbb, 0x2b, 0x1a, 0xab, 0xd3, 0x49, 0x1b, 0x8c, 0x0d, 0x2a, 0x88, 0xbd, 0x07, 0x78,
	0xba, 0xa3, 0xa0, 0xf1, 0x31, 0x1d, 0xef, 0x87, 0xd8, 0x2c, 0x7a, 0xfe, 0x1b, 0x9e, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xb9, 0x15, 0xae, 0xa9, 0xbe, 0x02, 0x00, 0x00,
}
